name: Monthly Playlist Update

# Schedule the action to run at 00:00 on the 1st of every month
on:
  schedule:
    - cron: "0 0 1 * *"  # At midnight on the first day of each month
  workflow_dispatch:  # Allows the action to be triggered manually

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Monthly Update
      run: curl -X GET https://spotify-top-monthly-playlist.onrender.com/run_monthly_update
      env:
        SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
        SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
        SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
